### ISSUE TITLE
When specifying multiple developers only 1 is added

### ISSUE THREAD

**Issue by hierynomus** [xvik/gradle-pom-plugin#1]
When using the attached build.gradle file, only 1 of the 2 developers is added to the generated pom.

[build.gradle.txt](https://github.com/xvik/gradle-pom-plugin/files/387958/build.gradle.txt)

**Comment by xvik** [comment]
Good point, thank you! The reason is aggressive merge logic: dev2 simply overrides first one. Will look how to fix it.

**Comment by xvik** [comment]
Released [1.0.3](https://github.com/xvik/gradle-pom-plugin/releases/tag/1.0.3)

**Comment by hierynomus** [comment]
Thanks for the fast fix!
