### ISSUE TITLE
Migration from convention to extension for Gradle 8

### ISSUE THREAD

**Issue by mayur9991** [xvik/gradle-pom-plugin#61]
Gradle has deprecated the concept of conventions with Gradle 8.
https://docs.gradle.org/8.4-rc-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions

Is there a plan to update plugin and remove deprecation warnings?

**Comment by xvik** [comment]
Oh, that's bad. Current pom declaration is possible only with convention (because convention could be a free closure and not a pre-defined structure like extension).

Anyway, I'll, of course, look how to workaround it. Thank you for the info!

**Comment by xvik** [comment]
Plugin updated, but not yet released. There would be now both static pom configuration like in maven-publish plugin and raw closure (as before). 

You can already look the [migration guide](https://github.com/xvik/gradle-pom-plugin?tab=readme-ov-file#migration-from-2x-to-3), just in case if you'll have any advice on naming (before plugin gets released).

Final release will appear, maybe, in a week, when I check it with related plugins.

**Comment by xvik** [comment]
[released](https://github.com/xvik/gradle-pom-plugin/releases/tag/3.0.0)
